- hosts: local
  become: true
  tasks:
  - name: "Set state as a fact"
    set_fact: state="{{state | default('started')}}"

  - name: "Create LXC Containers"
    lxc_container:
      name: "{{item}}"
      template: ubuntu
      state: "{{state}}"
      template_options: --release focal
      container_config:
        - "linux.kernel_modules=ip_tables,ip6_tables,netlink_diag,nf_nat,overlay"
        - "lxc.apparmor.profile=unconfined" 
        - "lxc.cap.drop=" 
        - "lxc.cgroup.devices.allow=a" 
        - "lxc.mount.auto=proc:rw sys:rw" 
        - "security.nesting=true"
        - "security.privileged=true"
    with_items:
      - "{{ controller_container }}"
      - "{{ worker_containers }}"
    register: containers_info

  - name: "Set hosts values for new created containers"
    # Set /etc/hosts to be able to access the containers by name.
    lineinfile:
      path: /etc/hosts
      regexp: " {{item.item}}$"
      line: "{{item.lxc_container.ips[0]}}     {{item.item}}"
      state: present
    with_items:
      "{{containers_info.results}}"
    when:
      state=="present"

  - name: "Unset hosts values for deleted containers"
    # Set /etc/hosts to be able to access the containers by name.
    lineinfile:
      path: /etc/hosts
      regexp: " {{item.item}}$"
      state: absent
    with_items:
      "{{containers_info.results}}"
    when:
      state=="absent"

  vars_files:
    - vars/containers.yaml
