# bridge: br-os
bridge: br-os
bridge_external: br-ext
gateway: 172.23.0.1
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDav74floCqNH69aWyyiSyNZy14szoUfQeOyVzNeYNiobyjH5ssRqxyQU3v5demphI6qx8AKV0sKEFrg7SH2Pfta4NHqRm2cgKHNGNkpr+vVrkVv/ZEwvZP7+JagtbyUWhjX/MGKx2+4YWdeaWQJ5NZ13RHJ6FpNSxpUqwbTwsd8gJJZhUyXPzzyeGMfnOdr7lEEQSTxkdBVQxjaKxeP8xTfnFpHKwSIp68XD2FQn+qv6UQJPEvosr5t1wOohLgQERTu4/e9rRo4iOeX71dPoXiFm52ce1A/oyyaSsYPBNZpEYUXgPsBmjZwzccWUuN+CHCGYNZOnOVBnsgm7ZPF4oh
controller_container:
  - name: controller
    ip: 10.0.3.2/24
    ip1: 172.23.16.2/24
    ip2: 172.23.32.2/24
compute_containers:
  - name: compute-01
    ip1: 172.23.16.5/24
    ip2: 172.23.32.5/24
  - name: compute-02
    ip1: 172.23.16.6/24
    ip2: 172.23.32.6/24
  - name: compute-03
    ip1: 172.23.16.7/24
    ip2: 172.23.32.7/24
