# Definition of the 2 briges I'll be using.
# br-ext: Wich will be attached to eth1 in LXC containers.
# br-os:  Which will be attached to eth1 in LXC containers for internal communications.
bridges:
  - name: br-ext
    ip: 172.23.16.1/24
    type: external
    network: 172.23.16.0
  - name: br-os
    ip: 172.23.32.1/24
    type: internal
    network:

bridge_external: "{{bridges[0].name}}"
bridge: "{{bridges[1].name}}"

# Gateway of external VMs
gateway: 172.23.16.1

# ssh-rsa public key to be added to the containes to be used to ssh the containers by Kolla
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDav74floCqNH69aWyyiSyNZy14szoUfQeOyVzNeYNiobyjH5ssRqxyQU3v5demphI6qx8AKV0sKEFrg7SH2Pfta4NHqRm2cgKHNGNkpr+vVrkVv/ZEwvZP7+JagtbyUWhjX/MGKx2+4YWdeaWQJ5NZ13RHJ6FpNSxpUqwbTwsd8gJJZhUyXPzzyeGMfnOdr7lEEQSTxkdBVQxjaKxeP8xTfnFpHKwSIp68XD2FQn+qv6UQJPEvosr5t1wOohLgQERTu4/e9rRo4iOeX71dPoXiFm52ce1A/oyyaSsYPBNZpEYUXgPsBmjZwzccWUuN+CHCGYNZOnOVBnsgm7ZPF4oh

# Definition of the Controller Container.
# -- No need for IP1 (IP in eth1) as it is an external network
# -- 172.23.32.2/24 in IP2 (IP in eth2)
controller_container:
  - name: oscontroller
    ip0: 10.0.3.2/24
    hw0: ca:fe:50:10:00:02
    ip1:
    hw1: ca:fe:50:10:01:02
    ip2: 172.23.32.2/24
    hw2: ca:fe:50:10:02:02


# Definition of the Compute Containers.
# -- No need for IP1 (IP in eth1) as it is an external network
# -- 172.23.32.5,6,7/24 in IP2 (IP in eth2)
compute_containers:
  - name: oscompute-01
    ip0: 10.0.3.50/24
    hw0: ca:fe:50:10:00:05
    ip1:
    hw1: ca:fe:50:10:01:05
    ip2: 172.23.32.5/24
    hw2: ca:fe:50:10:02:05
  - name: oscompute-02
    ip0: 10.0.3.60/24
    hw0: ca:fe:50:10:00:06
    ip1:
    hw1: ca:fe:50:10:01:06
    ip2: 172.23.32.6/24
    hw2: ca:fe:50:10:02:06
  - name: oscompute-03
    ip0: 10.0.3.62/24
    hw0: ca:fe:50:10:00:07
    ip1:
    hw1: ca:fe:50:10:01:07
    ip2: 172.23.32.7/24
    hw2: ca:fe:50:10:02:07
