apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikimedia
  labels:
    name: wikimedia-rs
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
      - wikimedia.ji
    secretName: wordpres-ji-tls 
  rules:
  - host: wikimedia.ji
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: wikimedia-svc
                port:
                  name: http

