apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
    - name: db
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: somwordpresspassword
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
