apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql-rs
spec:
  type: ClusterIP
  selector:
    name: mysql-rs
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
#      targetPort: 3306
