apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  labels:
    name: wordpress-rs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /wordpress(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: wordpress-svc
                port: 
                  name: http
