apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    name: wordpress-rs
spec:
  type: ClusterIP
  selector:
    name: wordpress-rs
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
