apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql-rs
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: mysql-rs
  strategy:
    type: RollingUpdate 
  template:
    metadata:
      name: db
      labels:
        name: mysql-rs
    spec:
      ## He borrado el nodeSelector. Ya no dependemos del nodo para tener el volumen disponible.
      containers:
        - name: db
          image: mysql:5.7
          ## Especificamos el volumen que queremos montar y donde queremos montarlo
          ## El volumen tenemos que definirlo en volumes
          volumeMounts:
            - name: nfs-pv-mysql
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: somwordpresspassword
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              value: wordpress
      ## Selecciona los volumenes persistentes previamente definidos y el claim sobre el volumen.
      volumes:
        - name: nfs-pv-mysql
          persistentVolumeClaim:
            claimName: nfs-pvc-mysql

