apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mysql
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # Tiene que coincidir con la configuración de un share en NFS.
    server: kcontroller
    path: "/storage/mysql/data"
